config/routes.rb
Rails.application.routes.draw do
  Spree::Core::Engine.add_routes do
    namespace :admin do
      resource :email_settings, only: [:edit, :update] do
        post :send_test_mail, on: :collection
      end
    end
  end
end

app/models/spree/email_setting.rb
module Spree
  class EmailSetting < ApplicationRecord
    belongs_to :store
  end
end

app/models/spree_store_mail_settings/configuration.rb
module SpreeStoreMailSettings
  class Configuration < ::Spree::Preferences::Configuration

   # Some example preferences are shown below, for more information visit:
   # https://dev-docs.spreecommerce.org/internals/preferences

   preference :enabled, :boolean, default: true
   # preference :dark_chocolate, :boolean, default: true
   # preference :color, :string, default: 'Red'
   # preference :favorite_number, :integer
   # preference :supported_locales, :array, default: [:en]
  end
end

app/models/spree_store_mail_settings/spree/store_decorator.rb
module SpreeStoreMailSettings
  module Spree
    module StoreDecorator
      def self.prepended(base)
        base.has_one :email_setting, class_name: 'Spree::EmailSetting', dependent: :destroy
      end
    end
  end
end

::Spree::Store.prepend SpreeStoreMailSettings::Spree::StoreDecorator

app/controllers/spree/admin/email_settings_controller.rb
module Spree
  module Admin
    class EmailSettingsController < ResourceController

      def update
        current_store.email_setting.update(email_setting_params)
        redirect_to edit_admin_email_settings_path
      end

      def edit
        unless @email_setting = current_store.email_setting
          @email_setting = Spree::EmailSetting.create!(store_id: current_store.id)
        end
      end

      def send_test_mail
        begin
          TestMailer.test_mail(try_spree_current_user.email, current_store).deliver_now
          flash[:success] = Spree.t('mail_test.success')
        rescue => e
          flash[:error] = Spree.t('mail_test.error', e: e)
        ensure
          redirect_to edit_admin_email_settings_path
        end
      end

      private
      def email_setting_params
        params.require(:email_setting).permit(:email_from, :email_bcc, :intercept_email, :mail_delivery, :store_id, smtp: [:domain, :address, :port, :secure_connection_type, :authentication, :user_name, :password])
      end
    end
  end
end

app/views/spree/admin/email_settings/_form.html.erb
<% content_for :page_title do %>
  <%= Spree.t('email_setting')%>
<% end %>

<% content_for :page_actions do %>
  <%= link_to Spree.t('send_test_mail'), send_test_mail_admin_email_settings_path, method: :post, class: 'btn btn-primary' %>
<% end %>

<%= form_with model: [:admin, @email_setting], :url => admin_email_settings_path do |form| %>
  <div>
    <h5>General</h5>
    <div class="mb-2">
      <%= form.check_box :mail_delivery %>
      <%= form.label :mail_delivery, class:'mb-2' %>
    </div>
    <div class="row">
      <div class="mb-2 col-6">
        <%= form.label :email_from %><br>
        <%= form.text_field :email_from , class:'form-control'%>
      </div>

      <div class="mb-2 col-6">
        <%= form.label :email_bcc %><br>
        <%= form.text_field :email_bcc, class:'form-control' %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label :intercept_email %><br>
        <%= form.text_field :intercept_email, class:'form-control' %>
      </div>
    </div>
    <h5>SMTP</h5>
    <div class="row">
      <div class="mb-2 col-6">
        <%= form.label 'SMTP Mail Domain' %><br>
        <%= form.text_field 'smtp[domain]', name: 'email_setting[smtp][domain]', class:'form-control', value: @email_setting.smtp['domain'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SMTP Mail Host' %><br>
        <%= form.text_field 'smtp[address]',name: 'email_setting[smtp][address]',  class:'form-control',  value: @email_setting.smtp['address'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SMTP PORT' %><br>
        <%= form.text_field 'smtp[port]', name: 'email_setting[smtp][port]', class:'form-control',  value: @email_setting.smtp['port'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SECURE CONNECTION TYPE' %><br>
        <%= form.text_field 'smtp[secure_connection_type]', name: 'email_setting[smtp][secure_connection_type]', class:'form-control',  value: @email_setting.smtp['secure_connection_type'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SMTP AUTHENTICATION TYPE' %><br>
        <%= form.text_field 'smtp[authentication]', name: 'email_setting[smtp][authentication]', class:'form-control', value: @email_setting.smtp['authentication'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SMTP USERNAME' %><br>
        <%= form.text_field 'smtp[user_name]', name: 'email_setting[smtp][user_name]', class:'form-control', value: @email_setting.smtp['user_name'] %>
      </div>

      <div class="mb-2 col-6">
        <%= form.label 'SMTP PASSWORD' %><br>
        <%= form.text_field 'smtp[password]', name: 'email_setting[smtp][password]', class:'form-control', value: @email_setting.smtp['password'] %>
      </div>
    </div>

    <div class="mt-4 d-flex justify-content-start">
      <%= form.submit class:'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/spree/admin/email_settings/edit.html.erb
<%= render 'form'%>